import './createDepartment';
import './createStudent';
import './createSubject';
import './updateDepartment';
import './updateSubject';
import './updateStudent';
import './removeStudent';
import './decrease_total_student_on_department';
import './decrease_total_student_on_subjects';
